# application.yml
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=northwind;encrypt=true;trustServerCertificate=true
    username: sa
    password: mbacke@221
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  hikari:
    pool-name: Northwind-Pool
    maximum-pool-size: 10
    minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none  # Ne pas créer/modifier les tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: dbo
        dialect: org.hibernate.dialect.SQLServerDialect